### ISSUE TITLE
lazy creation/deletion of variables and constraints

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/rust-gurobi#14]
Official API for C++ and some community-driven libs (like https://github.com/supermihi/gurobimh) support to add/remove variables without calling APIs.
It seems to be better than current implementation.

**Comment by leoyvens** [comment]
It is unfortunate that variables are no longer `Copy` having to write `&x + &y = 0` instead of `x + y = 0`. I wonder if there is a way around this, maybe if `rust-gurobi` gave unique indexes to variables and internally mapped them to the real indexes?

**Comment by ubnt-intrepid** [comment]
@leodasvacas
As you pointed out, writing constraints without borrowing is better than `&x + &y`. It was removed during the trial and error of the API.
I'll add derivation of `Copy` trait again until next release.
