### ISSUE TITLE
Call for maintainer

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/rust-gurobi#42]

**Comment by Darksonn** [comment]
I am interested in taking over. I'm looking to remove the Julia FFI I currently use to interact with gurobi, and this seems like a good way to do that.

**Comment by ubnt-intrepid** [comment]
@Darksonn Thank you for your help.
I've just sent an invitation request to your account as a collaborator for this repository.

**Comment by ubnt-intrepid** [comment]
@Darksonn Also added your account to crates.io's package owner list (both of `gurobi` and `gurobi-sys`).

**Comment by Darksonn** [comment]
Thank you! I have received the invites. It seems like the tag for v0.3.3 is further ahead in git history than the master branch. What's up with that?

**Comment by ubnt-intrepid** [comment]
It seems that I forgot pushing to remote when 0.3.3 was released :(

**Comment by Darksonn** [comment]
I fast-forwarded it.
