### ISSUE TITLE
Can we get the model.chgCoeff function?

### ISSUE THREAD

**Issue by ctriley** [ubnt-intrepid/rust-gurobi#48]
https://www.gurobi.com/documentation/9.0/refman/py_model_chgcoeff.html

This is extremely useful for column generation.

**Comment by Darksonn** [comment]
Hi. You are probably looking for [`Model::set_coeff`][1]. Please be aware that  #46 has not yet been published, so I recommend you use the version from git to get that bug fix.

I have a working column generation based application I recently wrote, so it can definitely be done as is.

[1]: https://docs.rs/gurobi/0.3.3/gurobi/struct.Model.html#method.set_coeff
