### ISSUE TITLE
write documentation

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/rust-gurobi#8]
- [x] ~~overview~~
- [x] installation
- [x] explanation of modules
  - [x] env
  - [x] model
  - [x] error

**Comment by leoyvens** [comment]
It's strange to have docs on `master` branch and to have source code on `gh-pages`. I think it would be better if `master` has only source and `gh-pages` has only docs.

**Comment by ubnt-intrepid** [comment]
@leodasvacas
As you pointed out , it is inappropriate that the source code is managed by `master` and `gh-pages`.
I'll remove documents from `master` branch until next release. 

Thank you for bringing it to my attention :)
